"""Generate PyInstaller version_info.txt from app.version."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.version import APP_AUTHOR, APP_COPYRIGHT_HOLDER, APP_NAME, __version__

OUT = ROOT / "packaging" / "version_info.txt"

major, minor, patch = (int(x) for x in __version__.split(".")[:3])
filevers = (major, minor, patch, 0)

content = f'''# UTF-8
# Auto-generated by scripts/generate_version_info.py — do not edit by hand.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers},
    prodvers={filevers},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          "040904B0",
          [
            StringStruct("CompanyName", "{APP_AUTHOR}"),
            StringStruct("FileDescription", "{APP_NAME}"),
            StringStruct("FileVersion", "{__version__}"),
            StringStruct("InternalName", "TelegramHashtagDownloader"),
            StringStruct("LegalCopyright", "Copyright (c) 2026 {APP_COPYRIGHT_HOLDER}"),
            StringStruct("OriginalFilename", "TelegramHashtagDownloader.exe"),
            StringStruct("ProductName", "{APP_NAME}"),
            StringStruct("ProductVersion", "{__version__}"),
          ],
        )
      ]
    ),
    VarFileInfo([VarStruct("Translation", [1033, 1200])]),
  ],
)
'''

OUT.write_text(content, encoding="utf-8")
print(f"Wrote {OUT}")
